server:
  port: 80

spring:
  mvc:
    view:
      prefix: /WEB-INF/templates/
      suffix: .jsp
  resources:
    static-locations: /WEB-INF/static/
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true

superkid:
  mail:
    username: replace me
    password: replace me
    receivers:
      - add email
      - add email
    host: smtp.gmail.com
    port: 587
    encoding: UTF-8
    auth: mail.smtp.auth
    authStatus: true
    starttls: mail.smtp.starttls.enable
    starttlsStatus: true