server:
  port: 80

spring:
  mvc:
    view:
      prefix: /WEB-INF/templates/
      suffix: .jsp
  resources:
    static-locations: /WEB-INF/static/
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true