server:
  port: 80

logging:
  path: ./log
  file: ${logging.path}/superkid-app.log

spring:
  mvc:
    view:
      prefix: /WEB-INF/templates/
      suffix: .jsp
  resources:
    static-locations: /WEB-INF/static/
  jpa:
    open-in-view: false
    generate-ddl: true

superkid:
  mail:
    username: replace me
    password: replace me