version: '3'
services:

  mysql:
    container_name: mysql
    image: mysql:8.0.16
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'superkid_service'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'