version: '3'
services:

  mysql-service:
    container_name: mysql
    image: mysql:8.0.16
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "superkid_service"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"

  superkid-service:
    container_name: superkid-service
    image:   vadimdissa/superkid-service:2.1.1
    ports:
      - "80:80"
    environment:
      spring.profiles.active: "dev"
      spring.datasource.url: "jdbc:mysql://mysql-service:3306/superkid_service"
      spring.datasource.username: "user"
      spring.datasource.password: "password"
      superkid.mail.username: "user@gmail.com"
      superkid.mail.password: "password"
      superkid.mail.receivers: "user1@gmail.com, user2@gmail.com"
      superkid.mail.host: "smtp.gmail.com"
      superkid.mail.port: "587"
      superkid.mail.encoding: "UTF-8"
      superkid.mail.auth: "mail.smtp.auth"
      superkid.mail.authStatus: "true"
      superkid.mail.starttls: "mail.smtp.starttls.enable"
      superkid.mail.starttlsStatus: "true"